AllCops:
  DisabledByDefault: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - "frontend/**/*"
    - "spec/fixtures/**/*"

Lint:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/RedundantDirGlobSort:
  Enabled: false

Lint/RedundantRequireStatement:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false
